### ISSUE TITLE
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

### ISSUE THREAD

**Issue by jimishio** [awslabs/aws-python-sample#7]
As per Readme.md I have done all the things mentioned over there still error exists.

Here is my ~/.aws/credentials (credentials are double checked with amazon user) : 

```
[default]
aws_access_key_id = 'AKIAIWX3MVLXSxxxxTQ'
aws_secret_access_key = 'CqERo84v2X9M0OyR8I2T+wEA0hi/siIxxxxxx'
```

changed bucket name getting created by sample python script to `jimish` 

@ Amazon console : user has access of `AmazonS3FullAccess`

Issue is still there. Please help

**Comment by LeoGSA** [comment]
I confirm. Issue is still here. I can list buckets, I can upload to buckets. But I can't create a bucket. I'm also getting this error.
Traceback (most recent call last):
  File "D:\aws-python-sample-master\test_s3.py", line 33, in <module>
    create_bucket('Leo_bucket')
  File "D:\aws-python-sample-master\test_s3.py", line 28, in create_bucket
    s3.create_bucket(Bucket=bucket_name)
  File "c:\Python34\lib\site-packages\botocore\client.py", line 312, in _api_cal
l
    return self._make_api_call(operation_name, kwargs)
  File "c:\Python34\lib\site-packages\botocore\client.py", line 601, in _make_ap
i_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling t
he CreateBucket operation: Access Denied

**Comment by jsr03126** [comment]
Great

**Comment by bprager** [comment]
Might not be related, but I just resolved an Ansible task using boto by running the script with sudo permission. The "Access denied" you get could be a local 'access denied'?

**Comment by ogyalcin** [comment]
@bprager who would have thought! That fixed my problem on OSX. Thanks

**Comment by NigarumOvum** [comment]
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied

I'm trying to deploy in heroku at this error appears, but in local development I'm able to connect RDS & S3 bucket.

If someone knows how to advance from here please save my day.
